# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'Example_iOS' do

  use_frameworks!

  pod 'cmark-gfm', :git => 'https://github.com/ghostcrying/swift-cmark.git', :tag => '0.0.3'

  pod 'Markdown', :path => '../../'

end
