# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Example_iOS' do
  use_frameworks!

  # pod 'cmark-gfm', :path => 'https://github.com/ghostcrying/swift-cmark.git', :tag => '0.0.2'

  pod 'Markdown', :path => '../../'

end
